// Code generated by Slice Machine. DO NOT EDIT.

import dynamic from "next/dynamic";

export const components = {
  alernating_text: dynamic(() => import("./AlernatingText")),
  big_text: dynamic(() => import("./BigText")),
  carausal: dynamic(() => import("./Carausal")),
  hero: dynamic(() => import("./Hero")),
  sky_dive: dynamic(() => import("./SkyDive")),
};
